-- Supabase SQL Editor: run this once to create/fix the portfolio contact inbox.
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 120),
  email text not null check (char_length(trim(email)) between 3 and 180),
  phone text not null check (char_length(trim(phone)) between 7 and 40),
  message text not null check (char_length(trim(message)) between 1 and 4000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'archived', 'rejected')),
  created_at timestamptz not null default now()
);

alter table public.contact_messages
add column if not exists phone text;

alter table public.contact_messages
add column if not exists created_at timestamptz not null default now();

update public.contact_messages
set email = 'missing-email@example.com'
where email is null or trim(email) = '';

update public.contact_messages
set phone = 'missing-phone'
where phone is null or trim(phone) = '';

alter table public.contact_messages
alter column email set not null;

alter table public.contact_messages
alter column phone set not null;

alter table public.contact_messages
drop constraint if exists contact_messages_email_length;

alter table public.contact_messages
add constraint contact_messages_email_length
check (char_length(trim(email)) between 3 and 180);

alter table public.contact_messages
drop constraint if exists contact_messages_phone_length;

alter table public.contact_messages
add constraint contact_messages_phone_length
check (char_length(trim(phone)) between 7 and 40);

alter table public.contact_messages
alter column status set default 'pending';

alter table public.contact_messages enable row level security;

drop policy if exists "Visitors can submit contact messages" on public.contact_messages;
drop policy if exists "Admin page can read contact messages" on public.contact_messages;
drop policy if exists "Allow anon insert contact messages" on public.contact_messages;
drop policy if exists "Allow anon read contact messages" on public.contact_messages;

create policy "Visitors can submit contact messages"
on public.contact_messages
for insert
to anon
with check (true);

-- This static portfolio uses the anon key in the browser, so this read policy
-- lets the admin page show messages after the hidden passcode screen.
create policy "Admin page can read contact messages"
on public.contact_messages
for select
to anon
using (true);

grant usage on schema public to anon;
grant usage on schema public to authenticated;
grant insert, select on public.contact_messages to anon;
grant insert, select on public.contact_messages to authenticated;

create index if not exists contact_messages_created_at_idx
on public.contact_messages (created_at desc);

create or replace function public.get_contact_messages_for_admin()
returns setof public.contact_messages
language sql
security definer
set search_path = public
as $$
  select *
  from public.contact_messages
  order by created_at desc nulls last;
$$;

grant execute on function public.get_contact_messages_for_admin() to anon;
grant execute on function public.get_contact_messages_for_admin() to authenticated;

notify pgrst, 'reload schema';
