services:
  db:
    image: postgres:latest
    container_name: backend_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: backend_api
    depends_on:
      - db
    env_file:
      - .env
    environment:

      DATABASE_URL: postgresql://postgres.iybendtdgpuvkgcqwken:[AngelsNeverCries00]@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
      PORT: 8000
      CLIENT_URL: https://portfolio-one-sigma-11.vercel.app/
    ports:
      - "8000:8000"

    volumes:
      - backend_db_data:/data

volumes:
  backend_db_data: